services:
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: spb_opensearch
    environment:
      - cluster.name=spb-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=false  # На Windows ставим false!
      

      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      
      # Пароль админа (для доступа)
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin123
      
      # Отключаем безопасность ТОЛЬКО ОДНИМ способом:
      # либо используйте эту строку:
      - DISABLE_SECURITY_PLUGIN=true
      # либо эту, но не обе сразу:
      # - plugins.security.disabled=true
      

      - DISABLE_INSTALL_DEMO_CONFIG=true
      

      - plugins.security.ssl.http.enabled=false
      

      - DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI=true
    
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    restart: unless-stopped

volumes:
  opensearch-data: